[package]
name = "aoc2025"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"


# eight
# kdtree = "0.8.0"

#nine
geo = "0.32.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["chrono"] }

# [profile.test]
# codegen-units = 1
# opt-level = 3
